company_name={
'20MICRONS':'20 Microns Limited',
'21STCENMGM':'21st Century Management Services Limited',
'3IINFOLTD':'3i Infotech Limited',
'3MINDIA':'3M India Limited',
'5PAISA':'5Paisa Capital Limited',
'A2ZINFRA':'A2Z Infra Engineering Limited',
'AAATECH':'AAA Technologies Limited',
'AAREYDRUGS':'Aarey Drugs & Pharmaceuticals Limited',
'AARON':'Aaron Industries Limited',
'AARTIDRUGS':'Aarti Drugs Limited',
'AARTISURF':'Aarti Surfactants Limited',
'AARVEEDEN':'Aarvee Denims & Exports Limited',
'AARVI':'Aarvi Encon Limited',
'AAVAS':'Aavas Financiers Limited',
'ABBOTINDIA':'Abbott India Limited',
'ABCAPITAL':'Aditya Birla Capital Limited',
'ABFRL':'Aditya Birla Fashion and Retail Limited',
'ABMINTLLTD':'ABM International Limited',
'ACC':'ACC Limited',
'ACCELYA':'Accelya Solutions India Limited',
'ACEINTEG':'Ace Integrated Solutions Limited',
'ADANIGREEN':'Adani Green Energy Limited',
'ADANIPOWER':'Adani Power Limited',
'ADANITRANS':'Adani Transmission Limited',
'ADFFOODS':'ADF Foods Limited',
'ADL':'Archidply Decor Limited',
'ADORWELD':'Ador Welding Limited',
'ADROITINFO':'Adroit Infotech Limited',
'AETHER':'Aether Industries Limited',
'AGARIND':'Agarwal Industrial Corporation Limited',
'AGRITECH':'Agri-Tech (India) Limited',
'HARDWYN':'Hardwyn India Limited',
'HARIOMPIPE':'Hariom Pipe Industries Limited',
'HARRMALAYA':'Harrisons  Malayalam Limited',
'HARSHA':'Harsha Engineers International Limited',
'HBSL':'HB Stockholdings Limited',
'HCG':'Healthcare Global Enterprises Limited',
'HDFCLIFE':'HDFC Life Insurance Company Limited',
'HDIL':'Housing Development and Infrastructure Limited',
'HEADSUP':'Heads UP Ventures Limited',
'HECPROJECT':'HEC Infra Projects Limited',
'HEG':'HEG Limited',
'HEIDELBERG':'HeidelbergCement India Limited',
'HGINFRA':'H.G. Infra Engineering Limited',
'HIL':'HIL Limited',
'HILTON':'Hilton Metal Forging Limited',
'HINDCON':'Hindcon Chemicals Limited',
'HINDOILEXP':'Hindustan Oil Exploration Company Limited',
'HINDPETRO':'Hindustan Petroleum Corporation Limited',
'HMVL':'Hindustan Media Ventures Limited',
'HONAUT':'Honeywell Automation India Limited',
'HONDAPOWER':'Honda India Power Products Limited',
'HPAL':'HP Adhesives Limited',
'HPIL':'Hindprakash Industries Limited',
'HPL':'HPL Electric & Power Limited',
'HUBTOWN':'Hubtown Limited',
'HUDCO':'Housing & Urban Development Corporation Limited',
'ICDSLTD':'ICDS Limited',
'ICEMAKE':'Ice Make Refrigeration Limited',
'ICICIGI':'ICICI Lombard General Insurance Company Limited',
'ICICIPRULI':'ICICI Prudential Life Insurance Company Limited',
'ICRA':'ICRA Limited',
'IDBI':'IDBI Bank Limited',
'IDEA':'Vodafone Idea Limited',
'IDFC':'IDFC Limited',
'IDFCFIRSTB':'IDFC First Bank Limited',
'IFBAGRO':'IFB Agro Industries Limited',
'IFBIND':'IFB Industries Limited',
'IFCI':'IFCI Limited',
'IFGLEXPOR':'IFGL Refractories Limited',
'IGARASHI':'Igarashi Motors India Limited',
'IGPL':'IG Petrochemicals Limited',
'IITL':'Industrial Investment Trust Limited',
'IL&FSENGG':'IL&FS Engineering and Construction Company Limited',
'IL&FSTRANS':'IL&FS Transportation Networks Limited',
'IMAGICAA':'Imagicaaworld Entertainment Limited',
'IMFA':'Indian Metals & Ferro Alloys Limited',
'IMPAL':'India Motor Parts and Accessories Limited',
'IMPEXFERRO':'Impex Ferro Tech Limited',
'INCREDIBLE':'INCREDIBLE INDUSTRIES LIMITED',
'INDBANK':'Indbank Merchant Banking Services Limited',
'INDIACEM':'The India Cements Limited',
'INDIAGLYCO':'India Glycols Limited',
'INDIAMART':'Indiamart Intermesh Limited',
'INDIANB':'Indian Bank',
'INDIANCARD':'Indian Card Clothing Company Limited',
'INDIGO':'InterGlobe Aviation Limited',
'INDIGOPNTS':'Indigo Paints Limited',
'INDLMETER':'IMP Powers Limited',
'INDORAMA':'Indo Rama Synthetics (India) Limited',
'INDOSTAR':'IndoStar Capital Finance Limited',
'INDOTECH':'Indo Tech Transformers Limited',
'INDOTHAI':'Indo Thai Securities Limited',
'INDOWIND':'Indowind Energy Limited',
'INDRAMEDCO':'Indraprastha Medical Corporation Limited',
'INDSWFTLAB':'Ind-Swift Laboratories Limited',
'INDUSINDBK':'IndusInd Bank Limited',
'INDUSTOWER':'Indus Towers Limited',
'INFOBEAN':'InfoBeans Technologies Limited',
'INFOMEDIA':'Infomedia Press Limited',
'INGERRAND':'Ingersoll Rand (India) Limited',
'INOXGREEN':'Inox Green Energy Services Limited',
'INOXWIND':'Inox Wind Limited',
'INSECTICID':'Insecticides (India) Limited',
'INSPIRISYS':'Inspirisys Solutions Limited',
'IOB':'Indian Overseas Bank',
'IOC':'Indian Oil Corporation Limited',
'IOLCP':'IOL Chemicals and Pharmaceuticals Limited',
'IONEXCHANG':'ION Exchange (India) Limited',
'IRFC':'Indian Railway Finance Corporation Limited',
'IRIS':'Iris Business Services Limited',
'IRISDOREME':'Iris Clothings Limited',
'ISFT':'Intrasoft Technologies Limited',
'ITDC':'India Tourism Development Corporation Limited',
'ITI':'ITI Limited',
'IVP':'IVP Limited',
'IWEL':'Inox Wind Energy Limited',
'IZMO':'IZMO Limited',
'JAIBALAJI':'Jai Balaji Industries Limited',
'JAIPURKURT':'Nandani Creation Limited',
'JASH':'Jash Engineering Limited',
'JAYNECOIND':'Jayaswal Neco Industries Limited',
'JBFIND':'JBF Industries Limited',
'JCHAC':'Johnson Controls - Hitachi Air Conditioning India Limited',
'JETAIRWAYS':'Jet Airways (India) Limited',
'JHS':'JHS Svendgaard Laboratories Limited',
'JINDALPHOT':'Jindal Photo Limited',
'JINDALPOLY':'Jindal Poly Films Limited',
'JKCEMENT':'JK Cement Limited',
'JKPAPER':'JK Paper Limited',
'JOCIL':'Jocil Limited',
'JPINFRATEC':'Jaypee Infratech Limited',
'JPOLYINVST':'Jindal Poly Investment and Finance Company Limited',
'JPPOWER':'Jaiprakash Power Ventures Limited',
'JSWENERGY':'JSW Energy Limited',
'JSWHL':'JSW Holdings Limited',
'JSWISPL':'JSW Ispat Special Products Limited',
'JUBLINDS':'Jubilant Industries Limited',
'JUSTDIAL':'Just Dial Limited',
'JWL':'Jupiter Wagons Limited',
'KAKATCEM':'Kakatiya Cement Sugar & Industries Limited',
'KALYANI':'Kalyani Commercials Limited',
'KALYANIFRG':'Kalyani Forge Limited',
'KALYANKJIL':'Kalyan Jewellers India Limited',
'KAMATHOTEL':'Kamat Hotels (I) Limited',
'KAMDHENU':'Kamdhenu Limited',
'KANPRPLA':'Kanpur Plastipack Limited',
'KAPSTON':'Kapston Services Limited',
'KARMAENG':'Karma Energy Limited',
'KAUSHALYA':'Kaushalya Infrastructure Development Corporation Limited',
'KAVVERITEL':'Kavveri Telecom Products Limited',
'KAYA':'Kaya Limited',
'KAYNES':'Kaynes Technology India Limited',
'KDDL':'KDDL Limited',
'KECL':'Kirloskar Electric Company Limited',
'KENNAMET':'Kennametal India Limited',
'KERNEX':'Kernex Microsystems (India) Limited',
'KESORAMIND':'Kesoram Industries Limited',
'KEYFINSERV':'Keynote Financial Services Limited',
'KFINTECH':'Kfin Technologies Limited',
'KHADIM':'Khadim India Limited',
'KHAITANLTD':'Khaitan (India) Limited',
'KHANDSE':'Khandwala Securities Limited',
'KICL':'Kalyani Investment Company Limited',
'KILITCH':'Kilitch Drugs (India) Limited',
'KIMS':'Krishna Institute of Medical Sciences Limited',
'ORIENTALTL':'Oriental Trimex Limited',
'PNBHOUSING':'PNB Housing Finance Limited',
'PODDARHOUS':'Poddar Housing and Development Limited',
'POWERGRID':'Power Grid Corporation of India Limited',
'POWERMECH':'Power Mech Projects Limited',
'PPAP':'PPAP Automotive Limited',
'PPL':'Prakash Pipes Limited',
'PPLPHARMA':'Piramal Pharma Limited',
'PRAENG':'Prajay Engineers Syndicate Limited',
'PRAKASH':'Prakash Industries Limited',
'PRECAM':'Precision Camshafts Limited',
'PRECOT':'Precot Limited',
'PREMEXPLN':'Premier Explosives Limited',
'PREMIER':'Premier Limited',
'PRESTIGE':'Prestige Estates Projects Limited',
'PRINCEPIPE':'Prince Pipes And Fittings Limited',
'PRITI':'Priti International Limited',
'PRIVISCL':'Privi Speciality Chemicals Limited',
'SPLIL':'SPL Industries Limited',
'SPORTKING':'Sportking India Limited',
'SREEL':'Sreeleathers Limited',
'SRF':'SRF Limited',
'SRHHYPOLTD':'Sree Rayalaseema Hi-Strength Hypo Limited',
'SRPL':'Shree Ram Proteins Limited',
'STAR':'Strides Pharma Science Limited',
'STARHEALTH':'Star Health and Allied Insurance Company Limited',
'STARPAPER':'Star Paper Mills Limited',
'STARTECK':'Starteck Finance Limited',
'STCINDIA':'The State Trading Corporation of India Limited',
'STEELCITY':'Steel City Securities Limited',
'STEL':'Stel Holdings Limited',
'STOVEKRAFT':'Stove Kraft Limited',
'STYRENIX':'Styrenix Performance Materials Limited',
'SUKHJITS':'Sukhjit Starch & Chemicals Limited',
'SUMEETINDS':'Sumeet Industries Limited',
'SUMICHEM':'Sumitomo Chemical India Limited',
'SUMIT':'Sumit Woods Limited',
'SUMMITSEC':'Summit Securities Limited',
'SUNDARMFIN':'Sundaram Finance Limited',
'SUNDRMBRAK':'Sundaram Brake Linings Limited',
'SUNFLAG':'Sunflag Iron And Steel Company Limited',
'SUPERHOUSE':'Superhouse Limited',
'SURYALAXMI':'Suryalakshmi Cotton Mills Limited',
'SURYAROSNI':'Surya Roshni Limited',
'SURYODAY':'Suryoday Small Finance Bank Limited',
'SUULD':'Suumaya Industries Limited',
'SWARAJENG':'Swaraj Engines Limited',
'SWELECTES':'Swelect Energy Systems Limited',
'SYNGENE':'Syngene International Limited',
'SYRMA':'Syrma SGS Technology Limited',
'TAINWALCHM':'Tainwala Chemical and Plastic (I) Limited',
'TALBROAUTO':'Talbros Automotive Components Limited',
'TANTIACONS':'Tantia Constructions Limited',
'TARAPUR':'Tarapur Transformers Limited',
'TARMAT':'Tarmat Limited',
'TASTYBITE':'Tasty Bite Eatables Limited',
'TATACHEM':'Tata Chemicals Limited',
'TATACOMM':'Tata Communications Limited',
'TATAELXSI':'Tata Elxsi Limited',
'TATAINVEST':'Tata Investment Corporation Limited',
'TATAMETALI':'Tata Metaliks Limited',
'TATASTLLP':'Tata Steel Long Products Limited',
'TATVA':'Tatva Chintan Pharma Chem Limited',
'TBZ':'Tribhovandas Bhimji Zaveri Limited',
'TCPLPACK':'TCPL Packaging Limited',
'TEAMLEASE':'Teamlease Services Limited',
'TECHIN':'Techindia Nirman Limited',
'TEGA':'Tega Industries Limited',
'TEJASNET':'Tejas Networks Limited',
'TEMBO':'Tembo Global Industries Limited',
'TERASOFT':'Tera Software Limited',
'TEXMOPIPES':'Texmo Pipes and Products Limited',
'TFCILTD':'Tourism Finance Corporation of India Limited',
'TFL':'Transwarranty Finance Limited',
'TGBHOTELS':'TGB Banquets And Hotels Limited',
'THANGAMAYL':'Thangamayil Jewellery Limited',
'THEINVEST':'The Investment Trust Of India Limited',
'TIMESGTY':'Times Guaranty Limited',
'VENKEYS':'Venkys (India) Limited',
'VENUSPIPES':'Venus Pipes & Tubes Limited',
'VENUSREM':'Venus Remedies Limited',
'VERANDA':'Veranda Learning Solutions Limited',
'VERTOZ':'Vertoz Advertising Limited',
'VESUVIUS':'Vesuvius India Limited',
'VETO':'Veto Switchgears And Cables Limited',
'VHL':'Vardhman Holdings Limited',
'VINDHYATEL':'Vindhya Telelinks Limited',
'VINEETLAB':'Vineet Laboratories Limited',
'VISAKAIND':'Visaka Industries Limited',
'VISASTEEL':'Visa Steel Limited',
'WEALTH':'Wealth First Portfolio Managers Limited',
'WEBELSOLAR':'Websol Energy System Limited',
'WEIZMANIND':'Weizmann Limited',
'WEL':'Wonder Electricals Limited',
'WELENT':'Welspun Enterprises Limited',
'WELINV':'Welspun Investments and Commercials Limited',
'WENDT':'Wendt (India) Limited',
'WEWIN':'WE WIN LIMITED',
'WHEELS':'Wheels India Limited',
'WHIRLPOOL':'Whirlpool of India Limited',
'WILLAMAGOR':'Williamson Magor & Company Limited',
'WIPL':'The Western India Plywoods Limited',
'WONDERLA':'Wonderla Holidays Limited',
'WORTH':'Worth Peripherals Limited',
'XCHANGING':'Xchanging Solutions Limited',
'XELPMOC':'Xelpmoc Design And Tech Limited',
'XPROINDIA':'Xpro India Limited',
'YUKEN':'Yuken India Limited',
'ZENITHEXPO':'Zenith Exports Limited',
'ZENITHSTL':'Zenith Steel Pipes & Industries Limited',
'ZIMLAB':'Zim Laboratories Limited',
'ZODIAC':'Zodiac Energy Limited',
'ZODIACLOTH':'Zodiac Clothing Company Limited',
'ZYDUSWELL':'Zydus Wellness Limited',
}